### ISSUE TITLE
Unable to load DLL 'pdfium.dll'

### ISSUE THREAD

**Issue by minguva** [pvginkel/PdfiumViewer#109]
Unable to load DLL 'pdfium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E).

I am able to use PDFViewer in Windows Application. It is working fine. But when I use the same codebase in OfficePlugin Application i am not able to load pdfium.dll. FYI OfficePlugin is ClassLibrary. Any help would be greatly appreciated. 

FYI.. I worked on my old computer. I think I am missing some components.

**Comment by denniscoppens** [comment]
If you got PdfiumViewer via Nuget, you'll get the native pdfium.dll in the X64 and X86 folders. Set "Copy to Output Directory" of these files to "Copy Always".

**Comment by minguva** [comment]
I tried this but still no luck.

**Comment by LMSCPL** [comment]
I'm having exactly the same issue.

We use Pdfium in one of our projects with no problems at all, but in the Outlook plugin application it always crashes with Unable to load DLL 'pdfium.dll'.

The x64 and x86 DLLs are set to Copy Always, and both directories and their DLLs are in the bin directory.

I did have similar issues with Entity Framework, that would sometimes work and sometimes crash saying it couldn't find its files. That turned out to be an issue with ShowDialog randomly setting the default directory to something other than the startup directory (a known issue), so simply getting the AppDomain.CurrentDomain.BaseDirectory and passing that through to Entity Framework solved the issue.

Given the documentation I read said that pdfium looks for the DLLs relative to the directory PdfiumViewer.dll is in, I thought it might be a similar issue, but I couldn't see any way to specify the DLL directory, and setting the current directory to the AppDomain.CurrentDomain.BaseDirectory before calling Pdfium didn't solve the issue.

**Comment by LMSCPL** [comment]
I fixed the issue by making a small change in the PdfiumViewer source:-

static NativeMethods()
{
    // Load the platform dependent Pdfium.dll if it exists.

    if (!TryLoadNativeLibrary(AppDomain.CurrentDomain.RelativeSearchPath))
        TryLoadNativeLibrary(Path.GetDirectoryName(typeof (NativeMethods).Assembly.Location));
}

I changed RelativeSearchPath to BaseDirectory (same fix as I used for Entity Framework), giving:-

static NativeMethods()
{
    // Load the platform dependent Pdfium.dll if it exists.

    if (!TryLoadNativeLibrary(AppDomain.CurrentDomain.BaseDirectory))
        TryLoadNativeLibrary(Path.GetDirectoryName(typeof (NativeMethods).Assembly.Location));
}

It now finds the DLLs correctly, and all works.

**Comment by minguva** [comment]
LMSCPL::: Thank you very much for the response. It worked..

**Comment by hidekuro** [comment]
I am facing this problem and I have to fix it urgently.
Is there a way to fix in my source without waiting for PdfiumViewer update?

**Comment by pvginkel** [comment]
PR #133 has been merged. I've not yet been able to do a release, but I'm not sure whether this solves the issue. @Snipx can you confirm this?

**Comment by Snipx** [comment]
I am not sure that the pull request I proposed would work for everybody having this issue, but I had similar issue and the fix worked for me and I think the approach in the pull request is a bit more generic than suggested here.
So the only thing I can confirm is that the fix solves similar issue for me :)

**Comment by pvginkel** [comment]
I decided to revert the #133 commit and take a different approach. I see a lot of different locations where the `pdfium.dll` can be stored and I don't think it's good idea to just keep adding permutations.

Instead, I've left the original implementation in tact and added a `PdfiumResolver` class that can be used as follows:

```csharp
PdfiumResolver.Resolve += (s, e) => e.PdfiumFileName = @"C:\Full\Path\To\pdfium.dll";
```

This expects an exact path to `pdfium.dll`. If you've stored the DLL in an architecture dependent path, you need to resolve this yourself, e.g. like this:

```csharp
PdfiumResolver.Resolve += (s, e) => e.PdfiumFileName = @"C:\Full\Path\To\" + (sizeof(IntPtr) == 8 ?
 "x64" : "x86") + @"\pdfium.dll";
```

Make sure you set this event before you touch the PdfiumViewer controls or the `PdfDocument` class. Once an attempt has been done to resolve the PDFium DLL, it won't try again.

**Comment by zsbzsb** [comment]
@pvginkel Would it be possible for you to include your last reply to this issue (the one talking about the ```PdfiumResolver``` class) to the readme? I just started using the library (totally awesome and easy to use library btw!) and it took me quite a while to find the above information.

**Comment by devTimmy** [comment]
The solution that worked for me is i tried installing **x86** nuget package library. Before i had installed **x64** library. You try substituting the two and see which works for you.
