### ISSUE TITLE
Go to a particular page on display

### ISSUE THREAD

**Issue by amadueke** [pvginkel/PdfiumViewer#16]
Hi Pieter, a great feature to look at adding to the PDFiumviewer would be to be able to go to a particular or specified page number upon display of the pdf. Thanks

**Comment by ArloJamesBarnes** [comment]
Although I have not tested it recently, I think this feature (which is a pretty obvious one, considering that most modern web browsers do this* for web pages) does not exist in the most prominent PDF solutions (Adobe Reader, Adobe Reader browser plugin, PDF.js, PDFium plain, evince, and so on), and so would be good to claim.

*where 'this' = returning to the vertical (and perhaps horizontal? Not usually an issue with well-designed web pages) position last viewed when a page is refreshed or otherwise reopened.

**Comment by pvginkel** [comment]
I've added a second toolbar to the demo project that shows how this can be used.

**Comment by amadueke** [comment]
Hi Pieter, thanks for this. I've download and incorporated the code into my project. I'm going to create another issue in regards to a request that I got from my company's business analysts. Thanks
