### ISSUE TITLE
Printouts are moved (resized?) to bottom-right corner.

### ISSUE THREAD

**Issue by pablot** [pvginkel/PdfiumViewer#27]
On physical printer (tested on 2 printers HP and EPSON) printouts are moved to bottom - right corner. Sometimes they has cutted right edge. I attached hard copies from pdfium and syncfusion. As you can see in syncfusion (bottom image) is in center of sheet, but in pdfium is moved (or resized?) to bottom-right corner. 

When I use XPS printer everything is ok, the issue is only on physical printers!

![pdfium](https://cloud.githubusercontent.com/assets/1227550/7809452/7bbf6b20-039a-11e5-9f09-891eb578d1b5.jpg)
![syncfusion](https://cloud.githubusercontent.com/assets/1227550/7809454/82608ae0-039a-11e5-93be-48119906bd57.jpg)

I have hope that i can check code and repair that in maybe 2 weeks from now. But if you have some time I will be very grateful.

**Comment by pvginkel** [comment]
Apparently printers have hard margin that .NET is kind enough to adjust for. The hard margin of a printer is the area where the printer cannot print anything (e.g. because it uses a mechanism to hold on to the paper or something like that) That's what you're seeing and why it does work in XPS (it doesn't have a hard margin). This is fixed in the latest version. The default setting differs from what e.g. Foxit does, but instead does what e.g. Word does. The default setting accounts for the hard margin. If you have stuff outside of the hard margin in the PDF document, it won't be printed. However, this does preserve the original scale of the document. You can change this setting on the PdfViewer using the DefaultPrintMode. The alternative is to scale the page into the printer margins.

**Comment by pablot** [comment]
Hej, thanks for your commit. It look's better, but... consider this images.
![cut_margin](https://cloud.githubusercontent.com/assets/1227550/7857006/9dbd1fbc-052d-11e5-8e2b-bb9cbcea3997.jpg)
![shrink_to_margin](https://cloud.githubusercontent.com/assets/1227550/7857009/a0b632d0-052d-11e5-8006-fdafc6fe1db8.jpg)

The first one is cut to margin, the second shrink to margin. In both cases the right margin is smaller than the left. It's not a very big deal for us, just info for you.

Have a nice sunny day, and thank for your support.

**Comment by pvginkel** [comment]
That is very strange though. If it's possible I would like to find out why this happens. Maybe we can gather some data. Could you try executing the following steps and gathering the result?:

* Start the demo application that is in the source tree of PdfiumViewer;
* Set a breakpoint in the `OnPrintPage` method in the `PdfPrintDocument` class (doesn't matter where);
* Note down the following information:
  * `_document.PageSizes[_currentPage]`;
  * `e.MarginBounds`;
  * `e.PageBounds`;
  * `e.PageSettings.HardMarginX` and `e.PageSettings.HardMarginY`;
  * `e.PageSettings.PaperSize`; and
  * `e.PageSettings.PrintableArea`.

I have tested this with an HP printer. Maybe your printer has some settings I didn't expect. This information could help me fix this issue.

**Comment by pablot** [comment]
No problem - checked on Konica Minolta and HP:
Konica:
_document.Pagesizes[0] => width = 595.0, height = 842.0
e.MarginBounds => x=100, y=100, width = 627, height = 969
e.PageBounds => x=0, y=0, width = 827, height = 1169
e.PageSettings.HardMargin => X = 16, Y=16
e.PageSettings.PaperSize = A4
e.PageSettings.Printablearea => x=16.666666, y = 16.66666, width = 793.3333, height = 1135.66663
HP:
_document.Pagesizes[0] => width = 595.0, height = 842.0
e.MarginBounds => x=100, y=100, width = 627, height = 969
e.PageBounds => x=0, y=0, width = 827, height = 1169
e.PageSettings.HardMargin => X = 23, Y=16
e.PageSettings.PaperSize = A4
e.PageSettings.Printablearea => x=23.666666, y = 16.66666, width = 779.3333, height = 1135.66663

On both printer printouts are a little bit on right|bottom side.

**Comment by pvginkel** [comment]
Can you provide me with a copy of the PDF you're printing?

**Comment by pablot** [comment]
Sorry for delay. It's work like this on every pdf. 
This is the first printout - cennik.
https://drive.google.com/file/d/0B4ipBKBloX5ESGRuS0p6cmFodW8/view?usp=sharing

**Comment by pvginkel** [comment]
Can you try https://gist.github.com/pvginkel/0826160bcae25372ad45, see whether that fixes this for you? This only supports `ShrinkToMargin`. `CutMargin` is not yet implemented.

**Comment by pablot** [comment]
We have tried that but the result is worst than in original 2.3.0.0:

![test_cennik](https://cloud.githubusercontent.com/assets/1227550/7882572/2fb7b09e-060f-11e5-9605-1fd442361705.jpg)

**Comment by pvginkel** [comment]
This honestly is diving me insane. I can't for the live of me figure out
what I'm doing wrong. What windows and .net version are you using? Maybe I
can try setting up a similar environment.

**Comment by pablot** [comment]
Hello, I will be figuring it out at Tuesday. Maybe at 10 - 12 a.m. (UTC+01:00). If you have time we can do it together (pair programming?) on my workstation in workplace.
Windows is 8.1 and project is in .net 4.0 full profile.

**Comment by pvginkel** [comment]
I would love to except that this overlaps with my work hours (I'm at UTC+2 and PdfiumViewer is a hobby project). If you do have a look at this, the Gist I send you should technically be correct. It correctly accounts for the properties the printer provides. Important things to take into account are:

* The `e.Graphics` only allows you to draw on the `e.PageSettings.PrintableArea` space, which is roughly the paper size minus `e.PageSettings.HardMarginX/Y`. This means that when you have a hard margin 10/10, coordinates 0, 0 on the `Graphics` instance will really be 10, 10;
* There are some DPI transformations. The base DPI Pdfium renders at is 96. The DPI transformation that is done is from the printer DPI (e.g. 600dpi) to the PdfiumViewer DPI (96dpi). First the output is scaled so that it fits within `e.PageSettings.PrintableArea` and this DPI including the `e.PageSettings.PrintableArea` adjusted for the final DPI is send to Pdfium. However, the method that renders the page does extra transformations if the provided DPI does not match the `Graphics` DPI.

My best guess is that the problem lies within the calculations for the DPI and rendered size. I think I would start with ripping out all these calculations (including the ones in `PdfDocument.Render` and try to get it to work that way. You could do this by creating an `internal` alternative of `PdfDocument.Render` named something like `PdfDocument.RenderWithoutTransform`. This method would look something like:

```cs
internal void RenderWithoutTransform(int page, Graphics graphics, int dpiX, int dpiY, int width, int height, PdfRenderFlags flags)
{
    if (graphics == null)
        throw new ArgumentNullException("graphics");
    if (_disposed)
        throw new ObjectDisposedException(GetType().Name);

    var dc = graphics.GetHdc();

    try
    {
        bool success = _file.RenderPDFPageToDC(
            page,
            dc,
            dpiX, dpiY,
            0, 0, width, height,
            FlagsToFPDFFlags(flags)
        );

        if (!success)
            throw new Win32Exception();
    }
    finally
    {
        graphics.ReleaseHdc(dc);
    }
}
```

I hope this helps a bit.

**Comment by pablot** [comment]
OK! I will check this tommorow and give you info. Thanks for your commitment!

**Comment by pablot** [comment]
Hello, 
That preview option was super :)
I check this, and we had problems with printers, not with your solution. Version 2.3.0.0 works perfectly now for us. Thank you 1 more time for commitment, and sorry for bad testing.

**Comment by pvginkel** [comment]
That's great news.
