### ISSUE TITLE
Document Rotation

### ISSUE THREAD

**Issue by Saran88** [pvginkel/PdfiumViewer#36]
Are you able to rotate a already loaded PDF document? I cannot seem to find any function for this inside of the code.

**Comment by pvginkel** [comment]
Thanks for the suggestion. This has been implemented and I've pushed a new version to NuGet with this functionality. Because of limitations in the Pdfium library, or my understanding of it, rotating the output does degrade performance. Please let me know if the performance impact is such that it needs to be addressed. If so, please create a new ticket for this.
