### ISSUE TITLE
Unable to load DLL ' Pdfium.dll'. Exception from HRESULT: 0xC000001D". 

### ISSUE THREAD

**Issue by tega90** [pvginkel/PdfiumViewer#52]
Just like the title says, this happens when i try to open a pdf in my .NET 2.0 application using pdfium. I'm running the application on windows xp service pack 3. Please help.

**Comment by hoppler** [comment]
Hi,

you have to make sure, that the x64 and x32 Folder in your Project gets copied into the outputfolder by rightklicking every file in the x64 and x32 folder in visual studio, go to properties and set "copy to outputfolder" = "copy always"

**Comment by pvginkel** [comment]
So, the problem is that the pdfium dll isn't compatible with Windows xp
anymore. The default configuration for a long time now has been like that,
but before I would modify the setup to include Windows xp compatibility.
However, the last time I recompiled it, they started using new C++ feature
which caused compilation problems that couldn't be easily fixed.

There however is some good news. The old ones are still there. You can
download them from
https://github.com/pvginkel/PdfiumViewer/tree/master/Libraries/Pdfium/Windows%20XP%20compatible.
You can use those instead of the ones that come with the nuget package. Do
note that they aren't updated anymore though.

If someone does know how to get Windows xp compatible versions of the
Pdfium library, please let me know.

**Comment by tega90** [comment]
@pvginkel thanks for your response. I've tried using that DLL you have suggested, but the problem remains :-/. Exactly the same message is shown.

**Comment by pvginkel** [comment]
That's very strange. You could try opening the DLL in
http://www.dependencywalker.com/. That should show you if dependencies are
missing. Besides that, are you sure you're using the same bit size (32-bit
or 64-bit) as the application is running under?

**Comment by tega90** [comment]
I have tried with dependencywalker and it resulted with two missing dlls: wer.dll and ieshims.dll. After manually adding those dlls, dep.walker showed bunch of missing dlls with similar names such as : API-MS-WIN-CORE-COM. Do you know anything about this? Thanks.

**Comment by pvginkel** [comment]
Those are the visual c++ redistributable. If you enter the full dll name on
Google, it should give you the version of then, probably 2012.
