### ISSUE TITLE
Opening a password protected PDF File

### ISSUE THREAD

**Issue by rearintok** [pvginkel/PdfiumViewer#59]
Hello Good Day,

I tried opening a password protected pdf document, the program crashes and said "vshost-clr1.exe has stopped working".....can you include support for password protected PDF Files. thank you very much

**Comment by pvginkel** [comment]
A few changes have been made:

* Opening an PDF document now properly checks for errors;
* `PdfException` now has a `Error` property with the error that occurred;
* `PdfDocument.Load` has gained an overload that takes an `IWin32Window`. When the document could not be opened because it was password protected, a password dialog is now shown. Alternatively you can implement such a dialog yourself.
