### ISSUE TITLE
Aliasing on Transparent Background

### ISSUE THREAD

**Issue by iamcarbon** [pvginkel/PdfiumViewer#6]
Is there a way to force the background color used for aliasing? It looks like text on a transparent background is aliased with the assumption that it will be rendered on black, not white.

Examples:

default (transparent)

![pdf-1](https://cloud.githubusercontent.com/assets/7537/5514155/a7a6de4a-87e8-11e4-9166-b6a7292e280e.png)

when rendered on a black graphics context:

![pdf-2](https://cloud.githubusercontent.com/assets/7537/5514159/c041b402-87e8-11e4-8e4e-f1ab0e085af4.png)

**Comment by pvginkel** [comment]
Could you make the PDF file available? That would make it a lot easier to solve this issue.

**Comment by mafshin** [comment]
I have this issue too. It's very annoying. Isn't there anyway to define a default background color and have auto anti-aliasing?

![capture](https://cloud.githubusercontent.com/assets/4930000/6085593/72c8dea6-ae50-11e4-94dd-02154767664f.JPG)


Sample PDF:
https://www.dropbox.com/s/4ssmby92rvnyh9u/Sample.pdf?dl=0

..

**Comment by pvginkel** [comment]
Thanks for the example PDF. That helps a lot. However, at the moment I have very little time to look at this issue. I will pick this up as soon as I can. Thanks for your patience.

**Comment by pvginkel** [comment]
I've looked at the issue and from what I can gather, the problem is that you're not using the PdfViewer class but rendering directly to a Bitmap or Graphics. I've implemented support for this. The PdfDocument class now has two new Render overloads which both return an Image. The demo application has been extended to call this using the Tools | Render to Bitmaps option. Have a look at the applicable code in MainForm.cs for how to call this.
