### ISSUE TITLE
Can not run on XP.But can bulid.

### ISSUE THREAD

**Issue by zbooa** [pvginkel/PdfiumViewer#63]
Thanks for this great project.
But I can't run it. I didn't make any changes.
My environment is VS2010 +.Net4.0 + XP
Compiler success. But open the PDF file, prompt as follows:
"Try to read or write protected memory. This usually indicates that other memory is corrupt."
Who can help me?

**Comment by IanYates** [comment]
You need an older version.  See commit https://github.com/pvginkel/PdfiumViewer/commit/d567bc3cbbd012db7ba294bfa17cffdb82e8a717

**Comment by pvginkel** [comment]
Actually the xp compatible dlls are still there. You just need to use them
manually. A while ago pdfium stopped supporting xp and I needed to get a
new version in because some important fixes were made. I copied the old
dlls to
https://github.com/pvginkel/PdfiumViewer/tree/master/Libraries/Pdfium/Windows%20XP%20compatible
to keep them available, but they're not in nuget anymore.

**Comment by zbooa** [comment]
@pvginkel Thanks>Thanks>Thanks>
over and over and over.

**Comment by pvginkel** [comment]
You're very welcome.
