### ISSUE TITLE
C#6 only.... Visual Studio 2015 only

### ISSUE THREAD

**Issue by rearintok** [pvginkel/PdfiumViewer#69]
if you use compiler lower than C#6, error occured

The name 'nameof' does not exist in the current context

**Comment by pvginkel** [comment]
That's right. I've updated Visual Studio and am using the latest version. The output is still compatible with .NET 2.0 since it's generating output for that framework version, but the source code requires Visual Studio 2015. This is not really an issue though. You can run different versions of Visual Studio side by side and you can a free version from https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx which should work with PdfiumViewer without issues.
