### ISSUE TITLE
Problem with Windows XP

### ISSUE THREAD

**Issue by unholyHub** [pvginkel/PdfiumViewer#70]
Hello

I wanted to test the WinForms Demo on Windows XP and give me exception

[Exception](https://gist.github.com/unholyHub/36726ea6ba87507846e49669ffc65ea9)

Could you please advise?

**Comment by pvginkel** [comment]
The latest version of the native DLL's are not compatible with Windows XP anymore since Pdfium dropped support for them. You can downloaded the latest compatible ones from https://github.com/pvginkel/PdfiumViewer/tree/master/Libraries/Pdfium/Windows%20XP%20compatible. Please try those.

**Comment by roy19831015** [comment]
> The latest version of the native DLL's are not compatible with Windows XP anymore since Pdfium dropped support for them. You can downloaded the latest compatible ones from https://github.com/pvginkel/PdfiumViewer/tree/master/Libraries/Pdfium/Windows%20XP%20compatible. Please try those.

because i want to add a self-define function to pdfium project ,in order that i can draw a crossline on the signature appearance, but neither the project build by PdfiumBuild or latest GOOGLE official version i build was not able to be compatible with XP, usually ended with strange errors.

so, i need the latest XP-compatible version of pdfium that you solve those problem instead of providing the release binary pdfium.dll, i have to make some changes inside it.

btw, the location i am staying is far from google, everytime i download something from google is suffering. i tried for a month, but still couldn't solve it.

thanks for helping ,it's a bit urgent.
