### ISSUE TITLE
Add Windows XP Compatible Pdfium.DLL support inside same project

### ISSUE THREAD

**Issue by dfdiego** [pvginkel/PdfiumViewer#82]
Hello, 

It would be fine to have the support for pdfium.dll libraries x64/x86 for both modern Windows and XP in the same PdfiumViewer assembly, I mean, in the NativeMethods.cs class, add some code to load the correct version of the 4 DLL according the architecture (x64/x86) and operating system version. So you put the two extra DLL in a WindowsXPFolder/x86 and WindowsXPFolder/x64, and the other two in x86 and x64 like now. In the method private static bool TryLoadNativeLibrary(string path) you intercept the XP OS and add the extra WindowsXPFolder folder to the final path.

What do you think ?

**Comment by pvginkel** [comment]
The problem is that the Windows XP version isn't really supported. It's build from an old source version which has known issues. The reason there is a non-XP compatible version at all is because it seems that the current build system doesn't support Windows XP at all.

However, I may be wrong. One problem is that I'm not really a hero at building Pdfium, and building Pdfium is far from trivial. If someone could have a look at the build script and write instructions on how to build a Windows XP compatible version from this, that would be terrific and I would love to get a Windows XP compatible DLL back in.

**Comment by dfdiego** [comment]
Ok, didn't know that XP DLLs were older version. In this case, I agree, it's better to not support XP at all.

Thanks

**Comment by pvginkel** [comment]
I've taken another stab at building Pdfium and took a different approach. In the `new-native-dll`'s branch, there are new x86 and x64 versions of the Pdfium DLL's.

These work without issues on Windows 10. Is it possible for you to check whether these work on Windows XP?

**Comment by pvginkel** [comment]
There we go. Someone else helped me out with a Window XP installation and after a few changes, we now have updated Windows XP compatible DLL's. See https://github.com/pvginkel/PdfiumViewer/tree/master/Libraries/Pdfium for more information.

To use these, just replace the default ones in your project.

**Comment by dfdiego** [comment]
Thank you! I've tested it on Windows XP x86 and Windows 10 x64 and I can confirm that it works fine.
