### ISSUE TITLE
Signature not being rendered

### ISSUE THREAD

**Issue by HusseinTaha** [pvginkel/PdfiumViewer#87]
Hello,

The signatures are not being displayed (digital signatures).
Can you help me about this, or tell me where do edit it?

**Comment by dfdiego** [comment]
Try to use PdfRenderFlags.Annotations in the flags on .Render() method. For me it worked, but I noticed that one of the newer version (the first one with double version without V8) didn't show them anymore, but I've to try the latest one.

**Comment by pvginkel** [comment]
@HusseinTaha does this solve your issue?

**Comment by iimax** [comment]
Tried to use PdfRenderFlags.Annotations in the flags on .Render() method. But it did not work with PdfiumViewer -Version 2.12.0

**Comment by pvginkel** [comment]
The problem is that the API changed. PdfiumViewer was using a render method that renders directly to a DC and takes a flag whether or not to draw annotations. This flag doesn't work anymore. Instead you're supposed to call `FPDF_FFLDraw` after you render the normal PDF content, but that only draws to a bitmap.

I've changed the rendering to now always draw to a bitmap and always call `FPDF_FFLDraw`. I'm using https://blogs.adobe.com/security/SampleSignedPDFDocument.pdf to test whether the signature is drawn (it wasn't and is now) and http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf to test whether a filled form is drawn (it wasn't and it is now).
